import RecoilRootWrapper from "@/recoil/wrapper";

import "./globals.css";
import localFont from 'next/font/local';

import { BaseContainer } from "@/components/container";

const pretendard = localFont({
  src: [
    {
      path: './Pretendard-Bold.woff2',
      weight: '700'
    },
    {
      path: './Pretendard-Light.woff2',
      weight: '300'
    },
    {
      path: './Pretendard-Medium.woff2',
      weight: '400'
    }
  ],
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  wrapper,
}: {
  children: React.ReactNode;
  wrapper: React.ReactNode;
}) {
  return (
    <html lang="en" className={pretendard.variable}>
      <body>
        <RecoilRootWrapper>
          <main className="w-screen h-screen font-pretendard">
            <BaseContainer>
              {wrapper}
              {children}
            </BaseContainer>
          </main>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
